trino:
  global:
    env: "dev"
    region: "region_test"

  accessControl:
    type: configmap
    refreshPeriod: 60s
    configFile: "rules.json"
    rules:
      rules.json: |-
        {
          "catalogs": [
            {
              "user": "admin",
              "catalog": "(tpch|system)",
              "allow": "all"
            },
            {
              "user": "alice",
              "catalog": "(tpch|system)",
              "allow": "all"
            }
          ]
        }
