global:
  env: "dev"
  region: "region_test"

server:
  node:
    environment: "{{ .Values.global.env }}_{{ .Values.global.region }}"
  workers: 1

jmx:
  enabled: true
  registryPort: 9080
  serverPort: 9081
  exporter:
    enabled: true
    image: bitnamisecure/jmx-exporter:latest
    pullPolicy: Always
    port: 5556
    configProperties: |
      startDelaySeconds: 0
      hostPort: 127.0.0.1:{{- .Values.jmx.registryPort }}
      rules:
        - pattern: 'trino.memory*'
        - pattern: 'trino.execution<name=QueryManager>*'
        - pattern: 'trino.execution<name=ClusterSizeMonitor>*'