apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  # ... (metadata is correct)
spec:
  generators:
    - git:
        files:
          - path: clusters/**/trino-values.yaml
        repoURL: https://github.com/t-manju/demo.git
        revision: main
  template:
    metadata:
      labels:
        app: trino
      name: trino-{{`{{path.basename}}`}}
    spec:
      destination:
        namespace: trino-{{`{{path.basename}}`}}
        server: https://kubernetes.default.svc
      project: default
      sources:
        - helm:
            valueFiles:
              # CORRECTED PATH: Use only the '{{path}}' variable
              - $values/{{`{{path}}`}}
          path: helm/trino
          repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
        - ref: values
          repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true