apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    # Use a Git generator to find the values files
    - git:
        repoURL: https://github.com/t-manju/demo.git
        revision: main
        files:
          - path: clusters/**/trino-values.yaml
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
      labels:
        app: trino
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'
      sources:
        - repoURL: https://trinodb.github.io/charts
          chart: trino
          targetRevision: 1.39.0
          helm:
            valueFiles:
              # Reference the values file using the '$values' syntax
              - $values/clusters/{{ .value.source.clusterFolder }}/common.yaml
              - $values/{{`{{path}}`}}/trino-values.yaml
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          ref: values # This is a special reference to the git generator's repo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false