apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clusterName: trino
            clusterFolder: stagedatalake
          - clusterName: trino1
            clusterFolder: stagedatalake

  template:
    metadata:
      name: '{.clusterName}}'
      labels:
        app: trino
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.clusterName}}'
      sources:
        # Helm chart source
        - repoURL: https://trinodb.github.io/charts
          chart: trino
          targetRevision: 1.39.0
          helm:
            valueFiles:
              - $values/clusters/{{.clusterFolder}}/common.yaml
              - $values/clusters/{{.clusterFolder}}/{{.clusterName}}/trino-values.yaml
        # Optional override values from your repo
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false