apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        repoURL:  {{ .Values.source.repoURL }}
        revision: {{ .Values.source.targetRevision}}
        files:
          - path: clusters/**/trino-values.yaml
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
      labels:
        app: trino
    spec:
      project: default
      sources:
        - repoURL: https://github.com/t-manju/demo.git
          path: helm/trino
          targetRevision: main
          helm:
            valueFiles:
              - $values/{{`{{path}}`}}/trino-values.yaml
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false
