apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - clusterFolder: stagedatalake
            clusterName: trino
          - clusterFolder: stagedatalake
            clusterName: trino1
  template:
    metadata:
      name: '{{.clusterName}}'
      labels:
        app: trino
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: {{.clusterName}}
      sources:
        - repoURL: https://github.com/t-manju/demo.git
          path: helm/trino
          targetRevision: main
          helm:
            valueFiles:
              - $values/clusters/stagedatalake/common.yaml
              - $values/clusters/stagedatalake/{{'{{.clusterName}}'}}-values.yaml
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false
