apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        repoURL:  {{ .Values.source.repoURL }}
        revision: {{ .Values.source.targetRevision}}
        files:
          - path: clusters/**/trino-values.yaml
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app: trino
    spec:
      project: default
      sources:
        - repoURL: {{ .Values.source.repoURL }}
          path: {{ .Values.source.targetRevision}}
          targetRevision: main
          helm:
            valueFiles:
              - $values/{{path}}/trino-values.yaml  # resolves to clusters/.../trino-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false
