apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        # Use a hardcoded Git URL and revision as generators do not support Helm templating
        repoURL: https://github.com/t-manju/demo.git
        revision: main
        files:
          - path: clusters/**/trino-values.yaml
  template:
    metadata:
      # Use a structured name for clarity
      name: 'trino-{{`{{path.basename}}`}}'
      labels:
        app: trino
    spec:
      project: default
      sources:
        - repoURL: https://github.com/t-manju/demo.git
          path: helm/trino
          targetRevision: main
          helm:
            valueFiles:
              # CORRECTED PATH: Use only {{path}} as it's the full path to the values file
              - $values/{{`{{path}}`}}
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        # The namespace should match the application name for consistency
        namespace: 'trino-{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false