apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        repoURL:  {{ .Values.source.repoURL }}
        revision:  {{ .Values.source.targetRevision }}
        # This path will find all trino-values.yaml files
        # It's flexible and will work for both trino/ and trino01/ folders
        files:
          - path: clusters/**/trino-values.yaml
  template:
    metadata:
      # Use path.basename to create a unique name for each application (e.g., stagedatalake-trino)
      name: '{{`{{path.basename}}-trino`}}' 
      labels:
        app: trino
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: {{ .Values.source.repoURL }}
          path: helm/trino
          targetRevision: {{ .Values.source.targetRevision }}
          helm:
            valueFiles:
              # Use the path variable from the generator.
              # This will resolve to the correct path for each cluster.
              - ../../{{`{{path}}`}} 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false