apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/t-manju/demo.git
        revision: main
        files:
          - path: clusters/**/trino-values.yaml

  template:
    metadata:
      name: trino-{{`{{path.basename}}`}}
      labels:
        app: trino
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: trino-{{`{{path.basename}}`}}
      sources:
        # Helm chart source
        - repoURL: https://trinodb.github.io/charts
          chart: trino
          targetRevision: 1.39.0
          helm:
            valueFiles:
              - $values/clusters/{{`{{path.basename}}`}}/common.yaml
              - $values/{{`{{path}}`}}/trino-values.yaml
        # Optional override values from your repo
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false
