apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd

spec:
  project: {{ .Values.project.name }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.trino.namespace }}
  sources:
    # First source: public Trino Helm chart with cluster overrides
    - repoURL: https://trinodb.github.io/charts
      chart: trino
      targetRevision: 1.39.0
      helm:
        releaseName: {{ .Values.trino.appName }}
        valueFiles:
          - {{ printf "$values/clusters/%s/trino-values.yaml" .Values.source.clusterFolder | quote }}

    - repoURL: {{ .Values.source.repoURL }}
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Validate=false
