apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/t-manju/demo.git
        revision: main
        files:
          - path: clusters/*/bootstrap.yaml   # scans all cluster bootstrap files
  template:
    metadata:
      name: '{{name}}'                       # generated Application name
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'               # from bootstrap.yaml
        chart: '{{chart}}'                    # wrapper chart: helm/trino
        targetRevision: '{{version}}'        # wrapper chart version
        helm:
          dependencyUpdate: true             # update dependencies (Trino chart)
          values: |
            trino:
              dependencyVersion: '{{dependencyVersionOverride}}'   # cluster Helm version
          valueFiles:
            {{- range $file := .valueFiles }}
            - $values/{{ $file }}
            {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground