apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        repoURL: {{ .Values.source.repoURL }}
        revision: {{ .Values.source.targetRevision }}
        files:
          # - path: clusters/*/trino-values.yaml   # points to the YAML files, not directories
          - path: {{ printf "clusters/%s/*/trino-values.yaml" .Values.source.clusterFolder | quote }}

  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
      labels:
        app: '{{`{{path.basename}}`}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.project.name }}
      sources:
        - repoURL: {{ .Values.source.repoURL }}
          targetRevision: {{ .Values.source.targetRevision }}
          path: helm/trino
          helm:
            valueFiles:
            - {{ printf "$values/clusters/%s/common.yaml" .Values.source.clusterFolder | quote }}
            - $values/{{`{{path}}`}}/trino-values.yaml
        # 2. Reference repo to enable $values resolution
        - repoURL: {{ .Values.source.repoURL }}
          targetRevision: {{ .Values.source.targetRevision }}
          ref: values

      destination:
        server: {{ .Values.destination.server }}
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false