apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.source.repoURL }}
        revision: main
        files:
          - path: {{ printf "clusters/%s/trino-values.yaml" .Values.source.clusterFolder | quote }}
  template:
    metadata:
      name: {{ .Values.trino.appName }}-{{ .Values.source.clusterFolder }}
    labels:
      app: {{ .Values.trino.appName }}-{{ .Values.source.clusterFolder }}
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.project.name }}
      destination:
        server: {{ .Values.destination.server }}
        namespace: {{ .Values.trino.namespace }}
      source:
        repoURL: https://trinodb.github.io/charts   # public Helm chart repo
        chart: trino
        targetRevision: 1.39.0
        helm:
          releaseName: {{ .Values.trino.appName }}
          valueFiles:
            - {{ printf "../../clusters/%s/trino-values.yaml" .Values.source.clusterFolder | quote }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false