apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        repoURL: {{ .Values.source.repoURL }}
        revision: main
        files:
        - path: {{ printf "clusters/%s/trino-values.yaml" .Values.source.clusterFolder | quote }}
  template:
    metadata:
      name: '{{ .Values.source.clusterFolder }}-trino'
      labels:
        app: '{{ .Values.source.clusterFolder }}-trino'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: {{ .Values.source.repoURL }}
        targetRevision: main
        path: helm/trino
        helm:
          valueFiles:
          - values.yaml
          - ../../clusters/{{ .Values.source.clusterFolder }}/trino-values.yaml
      destination:
        server: {{ .Values.destination.server }}
        namespace: {{ .Values.trino.namespace }}
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - Validate=false