apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clusterFolder: stagedatalake
            clusterName: trino
          - clusterFolder: stagedatalake
            clusterName: trino1
  template:
    metadata:
      labels:
        app: trino
      name: trino-{{.clusterName | lower}}
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: trino-{{.clusterName | lower}}
      sources:
        - repoURL: https://trinodb.github.io/charts
          chart: trino
          targetRevision: 1.39.0
          helm:
            valueFiles:
              - values/common.yaml
              - values/{{.clusterFolder}}/{{.clusterName}}/trino-values.yaml
        - repoURL: https://github.com/t-manju/demo.git
          targetRevision: main
          path: clusters/{{.clusterFolder}}/{{.clusterName}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false