apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.destination.server }}
    namespace: trino
  sources:
    - repoURL: {{ .Values.source.repoURL }}
      targetRevision: {{ .Values.source.targetRevision }}
      path: helm/trino
      helm:
        valueFiles:
          - {{ printf "../../clusters/%s/trino-values.yaml" .Values.source.clusterFolder | squote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Validate=false
