apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/t-manju/demo.git
        revision: main
        files:
          - path: clusters/*/bootstrap.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          dependencyUpdate: true
          values: |
            trino:
              dependencyVersion: '{{dependencyVersionOverride}}'
          valueFiles:
            - $values/helm/trino/values.yaml
            - $values/clusters/stagedatalake/trino-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground