apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
spec:
  generators:
    - git:
        repoURL: {{ .Values.source.repoURL }}
        revision: {{ .Values.source.targetRevision }}
        files:
          - path: clusters/*/trino-values.yaml
  template:
    metadata:
      name: '{{path.basename}}-trino'
      labels:
        app: trino
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.project.name }}
      sources:
        # Umbrella chart (your repo)
        - repoURL: {{ .Values.source.repoURL }}
          targetRevision: {{ .Values.source.targetRevision }}
          path: helm/trino
          helm:
            valueFiles:
              - $values/helm/trino/values.yaml
              - $values/{{path}}   # cluster-specific trino-values.yaml
      destination:
        server: {{ .Values.destination.server }}
        namespace: {{ .Values.trino.namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false