apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.source.repoURL }}
        revision: main
        directories:
          - path: clusters/stagedatalake
  template:
    metadata:
      name: {{ .Values.trino.appName }}-{{path.basename}}
    labels:
      app: {{ .Values.trino.appName }}
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.project.name }}
      destination:
        server: {{ .Values.destination.server }}
        namespace: {{ .Values.trino.namespace }}
      source:
        repoURL: {{ .Values.source.repoURL }}
        targetRevision: main
        path: helm/trino
        helm:
          releaseName: {{ .Values.trino.appName }}-{{path.basename}}
          valueFiles:
            - helm/trino/values.yaml
            - {{path}}/trino-values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false