apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trino
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.source.repoURL }}       # Use SSH for ArgoCD
        revision: main
        files:
          # Pull cluster-specific overrides for stagedatalake
          - path: argocd-apps/clusters/stagedatalake/*.yaml
  template:
    metadata:
      name: {{ .Values.trino.appName }}
      labels:
        app: {{ .Values.trino.appName }}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.project.name }}
      destination:
        server: {{ .Values.destination.server }}
        namespace: {{ .Values.trino.namespace }}
      sources:
        - repoURL: {{ .Values.source.repoURL }}
          targetRevision: main
          path: argocd-apps/helm/trino
          helm:
            chart: trino
            valueFiles:
              - argocd-apps/helm/apps/values.yaml                                      # global values
              - argocd-apps/clusters/stagedatalake/trino-values.yaml                        # cluster-specific overrides
        - repoURL: {{ .Values.source.repoURL }}
          targetRevision: main
          ref: values
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Validate=false