accessControl:
  enabled: false
  rules:
    rules.json:
      catalogs:
        - group: admin
          allow: all
      schemas:
        - group: admin
          allow: read-only

vaultSecret:
  enabled: true
  secretFile: |
    secret-key: dev-secret-value
    another-key: another-value

