# Corrected helm/trino/values.yaml
accessControl:
  enabled: false
  rules:
    rules.json: {}

vaultSecret:
  enabled: false
  secretFile: ""

trino-public:
  jmx:
    enabled: true
    registryPort: 9080
    serverPort: 9081
    exporter:
      enabled: true
      image: bitnamisecure/jmx-exporter:latest
      pullPolicy: Always
      port: 5556
      configProperties: |
        startDelaySeconds: 0
        # Corrected templating path
        hostPort: 127.0.0.1:{{ .Values.trino-public.jmx.registryPort }}
        rules:
          - pattern: 'trino.memory*'
          - pattern: 'trino.execution<name=QueryManager>*'
          - pattern: 'trino.execution<name=ClusterSizeMonitor>*'